### ISSUE TITLE
On windows 10 you can't restart snake example if you hit left wall

### ISSUE THREAD

**Issue by lesleyrs** [VincentFoulon80/console_engine#19]
**Describe the bug**
When you lose the game after hitting the left "wall" you can no longer restart the game with `space`. I tried to find out why but I have no clue. The game is still running telling you to press space, but it doesn't react to it.

**Additional context**
Windows 10, Windows terminal and Console host both have the issue.

**Comment by VincentFoulon80** [comment]
It wasn't an issue specific to Windows, but instead a softlock caused by the reset code not properly setting back to the starting point. The issue should be fixed on version 2.5.1

Thank you for the report!
