### ISSUE TITLE
Is it possible to stop the buffer from overflowing if you re-draw the entire screen?

### ISSUE THREAD

**Issue by lesleyrs** [VincentFoulon80/console_engine#25]
This is not directly about console_engine, but I'm trying to do something similar with just crossterm.

But I noticed that if I try to draw too much at once with queue, MoveTo and Print it will always immediately flush before it reaches the flush function.

I was looking at how you did it https://github.com/VincentFoulon80/console_engine/blob/d56ea01e9c6d026d612ad90fc3878faad7a270d0/src/lib.rs#L572

but the main difference is that you just try to avoid drawing as often for unchanged chars. Is that the only workaround for this, or are you doing something else that I missed?

**Comment by lesleyrs** [comment]
Yea all I'm doing right now is just filling a full screen (actual screen) with dots which is a lot. I think it takes about 40 ms if I saw correctly (debug mode).

However speed is not my problem right now, I set the frame rate at 1 per second but because it immediately flushes if I draw more than a few rows it's just ignored and flushes instantly. Then whatever is drawn on top either flickers or doesn't show.

The part that I don't understand is that avoiding overdrawing can't be the fix to my problem as the FIRST frame in console_engine already loads the way it should.

In console_engine if you call:
`let mut engine = console_engine::ConsoleEngine::init(160, 45, 1).unwrap();`

It draws the entire screen (for me anyway) after waiting the full 1 second which is correct.

But my behavior on a simple project is when I draw the full screen this way it just flushes instantly, no waiting unless I draw a tiny area.

**Comment by lesleyrs** [comment]
Ok some friendly guy in the crossterm discord helped me solve the problem. I had to replace:
`let mut stdout = stdout();`
with
`let mut stdout = BufWriter::with_capacity(640000, stdout());`

I guess the reason you didn't need to do this is because you are using screens as the buffer and that magically solves it? Problem solved anyway :D

**Comment by VincentFoulon80** [comment]
Interesting to know though, thank you for reporting back !
