### ISSUE TITLE
How to see errors from console engine?

### ISSUE THREAD

**Issue by gravit22** [VincentFoulon80/console_engine#4]
I have no idea hot effectively check errors during executions. 
I do cargo run => out.txt right now, and then I see the errors in the terminal, but it is not efficient.

**Comment by VincentFoulon80** [comment]
Hello ! Thank you for opening this issue.
I'm working on implementing a panic hook when using console_engine. For now it works but I still need to figure out how to properly display the message because the terminal prompt is written above it.
I should have something done soon.

**Comment by gravit22** [comment]
Hello. Thank you for reply. That would be great. This is the only significant problem I found in this engine. Otherwise, it works great.
I wish you luck in solving this problem.

**Comment by VincentFoulon80** [comment]
The issue has been fixed, into [Release 1.2.0](https://github.com/VincentFoulon80/console_engine/releases/tag/1.2.0)

**Comment by VincentFoulon80** [comment]
@gravit22 I forgot to ask you, is the bug fixed with this new version ?

**Comment by gravit22** [comment]
> @gravit22 I forgot to ask you, is the bug fixed on your side with this new version ?

Yeah. I can see the errors now. Thank you.
